### ISSUE TITLE
Would be great to have an ARM build of this container available

### ISSUE THREAD

**Issue by mikeyjarvis19** [JakeWharton/plex-auto-trash#1]
Apologies if this isn't the correct place to raise this, but would love to use this on my ARM based server, but it seems like it's only built for linux/amd64 at the moment.

**Comment by JakeWharton** [comment]
Sure, I'll give it a shot.

**Comment by JakeWharton** [comment]
So before doing this I'm going to migrate to a custom JRE built using the latest JDK (18) which will shrink the container size by about 75%. Then supporting this just means using buildx on CI to build the multiple architectures.

**Comment by thatbritguy** [comment]
Is this still in the pipeline? I've just switched to an ARM based machine and discovered this is the only container I use that doesn't have an arm build.

**Comment by austinarchibald** [comment]
Also wondering this. Got sick of upgrading a movie, only to have Plex think it's a new movie and add it to the Recently Added movies, so I turned off automatic trash empty. But then it causes issues when you forget to manually empty trash. This container will help me a lot. I just deployed it on docker, but not sure if it'll work or not. 

```
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00_bootstrap.sh: executing... 
[cont-init.d] 00_bootstrap.sh: exited 0.
[cont-init.d] 00_settimezone.sh: executing... 
[cont-init.d] 00_settimezone.sh: exited 0.
[cont-init.d] 10-cron.sh: executing... 

NOTE: Define HEALTHCHECK_ID with https://healthchecks.io to monitor sync job

Initializing cron

12 * * * *

[cont-init.d] 10-cron.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

Update, saw this. Hmm. Not an incorrect url and token (which works fine for plex-meta-manager in docker as well).

```
Exception in thread "main" com.jakewharton.plex.HttpException: 401 Unauthorized
	at com.jakewharton.plex.OkhttpKt$awaitString$2$1.onResponse(okhttp.kt:23)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by aniqueta** [comment]
Is an arm64 Docker build still planned? Was wondering why this wasn't working… Thanks

**Comment by JakeWharton** [comment]
Let me know if you have any problems.

**Comment by aniqueta** [comment]
Thanks for the quick response @JakeWharton 

I'm not sure if it's working, to be honest. 

For one, for some reason the Docker Compose environment variable for the cron schedule is not passing correctly. In the container console, PLEX_AUTO_TRASH_CRON is being set to `"0 bin lib sync.sh bin lib sync.sh bin lib sync.sh *"` (quotes included). 

My compose file is as follows

```
services:
  plex-auto-trash:
    container_name: plex-auto-trash
    image: jakewharton/plex-auto-trash:latest
    restart: unless-stopped
    environment:
      - PLEX_AUTO_TRASH_TOKEN=XXXXXXXXXXXX
      - PLEX_AUTO_TRASH_BASE_URL="http://XXX.XXX.XXX.XXX:32400"
      - PLEX_AUTO_TRASH_CRON="0 * * * *"
#Optional:
      - PLEX_AUTO_TRASH_IDLE_MINUTES=5
#      - "PLEX_AUTO_TRASH_HC_ID=..."
#      - "PLEX_AUTO_TRASH_HC_HOST=…"
```

The other environment variables are passing correctly, and other containers are able to reach Plex using the same token and URL. (Note, I had to change the quotes/syntax, since I don't think the readme is right?)

This may require another a separate issue to be created?

Is there a way to debug this more thoroughly?

Thanks.
